on: push
jobs: 
  build-job:
    name: Build VS Code Extension
    runs-on: windows-latest
    steps:
      - name: Check Node version
        run: node --version
      - name: Check NPM Version
        run: npm --version
      - name: Install required NPM Package
        run: npm install -g @vscode/vsce
      - name: Checkout code from GitHub
        uses: actions/checkout@v3        
      - name: Build VSIX
        working-directory: ./workmanagermacrosyntaxhighlight
        run: vsce package
      - name: Upload VSCode Extension Artifact
        uses: actions/upload-artifact@v3
        with:
          name: VSCode-Extension
          path: workmanagermacrosyntaxhighlight/**/workmanagermacrosyntaxhighlight-\d+\.\d+\.\d+\.vsix/*
        
