on: push
jobs: 
  build-project:
    name: Build VS Code Extension
    runs-on: windows-latest
    steps:
      - name: Check Node version
        run: node --version
      - name: Check NPM Version
        run: npm --version
      - name: Install required NPM Package
        run: npm install -g @vscode/vsce
      - name: Checkout code from GitHub
        uses: actions/checkout@v3        
      - name: Build VSIX
        working-directory: ./workmanagermacrosyntaxhighlight
        run: vsce package
      - name: Upload VSCode Extension Artifact
        uses: actions/upload-artifact@v3
        with:
          name: VSCode-Extension
          path: workmanagermacrosyntaxhighlight/workmanagermacrosyntaxhighlight-0.0.1.vsix
  release-project:
    name: Release VS Code Extension
    runs-on: windows-latest
    needs: build-project
    steps:
      - name: Download VSCode Extension Artifact
        uses: actions/download-artifact@v3
        with:
          name: VSCode-Extension
      - name: Test artifact download
        run: ls -R
          
  
